Repository MarianMalvin/phoqer, pull requests merged in 2021-06, with the labels that each got.

#174 #166 Chat API
  FastAPI/chats/__init__.py
  FastAPI/chats/chats.py
  FastAPI/chats/crud.py
  FastAPI/chats/schemas.py
  FastAPI/chats/tests/__init__.py
  FastAPI/chats/tests/conftest.py
  FastAPI/chats/tests/tests.py
  FastAPI/config.py
  FastAPI/main.py
Labels: BE

#175 ua language, tooltip for favorite
  frontend/assets/__tests__/config.spec.ts
  frontend/assets/months.ts
  frontend/components/common/offers/offers-card/index.tsx
  frontend/components/layout/header/lang/index.tsx
  frontend/components/layout/meta/index.tsx
  frontend/hooks/month.hook.ts
  frontend/next.config.js
  frontend/translations/index.ts
  frontend/translations/locales/ua.json
Labels: FE

#178 Search fix
  FastAPI/chats/crud.py
  FastAPI/chats/tests/tests.py
  FastAPI/offers/crud.py
  FastAPI/offers/schemas.py
  FastAPI/users/utils.py
Labels: BUG

#179 Альфа версия чата на сокетах
  .github/workflows/main.yml
  FastAPI/chats/chats.py
  FastAPI/chats/crud.py
  FastAPI/config.py
  FastAPI/offers/crud.py
  FastAPI/offers/offers.py
  FastAPI/offers/tests/tests.py
  FastAPI/users/utils.py
Labels: BE

#180 Add GitHub hooks frontend
  frontend/.husky/.gitignore
  frontend/.husky/pre-commit
  frontend/components/common/auth/forgot-pass-form/forgot-pass.spec.tsx
  frontend/components/common/auth/join-form/__snapshots__/join-form.spec.tsx.snap
  frontend/components/common/auth/join-form/join-form.spec.tsx
  frontend/components/common/auth/login-form/login-form.spec.tsx
  frontend/jest.config.js
  frontend/package.json
  frontend/yarn.lock
  yarn.lock
Labels: FE

#181 Dependencies frontend
  frontend/components/common/auth/forgot-pass-form/__snapshots__/forgot-pass.spec.tsx.snap
  frontend/components/common/auth/login-form/__snapshots__/login-form.spec.tsx.snap
  frontend/package.json
  frontend/server.js
  frontend/yarn.lock
Labels: FE

#182 Meta tegs
  frontend/next-sitemap.js
  frontend/package.json
  frontend/yarn.lock
Labels: FE

#185 Add requirements to backend
  FastAPI/build/requirements.txt
  FastAPI/chats/tests/tests.py
Labels: BE

#188 api for public profile offers
  FastAPI/offers/offers.py
  FastAPI/offers/schemas.py
  FastAPI/offers/tests/tests.py
Labels: BE
