Repository MarianMalvin/phoqer, pull requests merged in 2021-04, with the labels that each got.

#95 Meta tags
  frontend/components/Common/Meta/index.tsx
  frontend/components/Pages/Profile/Private/Messages/ChatConversation/index.tsx
  frontend/public/about.jpeg
  frontend/public/sw.js
Labels: FE

#98 Fix frontend build
  frontend/package.json
  frontend/public/sw.js
  frontend/yarn.lock
Labels: BUG

#92 #66 return offer_id instead of 203
  FastAPI/build/requirements.txt
  FastAPI/offers/crud.py
  FastAPI/offers/offers.py
  FastAPI/offers/tests/tests.py
Labels: BE

#106 New query string strategy for search
  frontend/assets/config.ts
  frontend/assets/helpers.ts
  frontend/assets/routes.ts
  frontend/assets/template.ts
  frontend/components/Common/Auth/ForgotPassForm/index.tsx
  frontend/components/Common/Auth/JoinForm/index.tsx
  frontend/components/Common/Auth/LoginForm/index.tsx
  frontend/components/Common/LoadMore/Pagination/index.tsx
  frontend/components/Common/NavTabs/Profile/SettingsNav/index.tsx
  frontend/components/Common/Offers/OffersCard/index.styles.ts
  frontend/components/Common/Offers/OffersCard/index.tsx
  frontend/components/Common/Preloaders/Progress/index.tsx
  frontend/components/Common/ProfileCard/index.tsx
  frontend/components/Common/Search/OptionsDesktop/index.tsx
  frontend/components/Common/Search/index.tsx
  frontend/components/Layout/Meta/index.tsx
  frontend/components/Pages/Offers/Edit/EditContentForm/StepOne/index.tsx
  frontend/components/Pages/Offers/Edit/EditContentForm/StepTwo/index.tsx
  frontend/components/Pages/Offers/Edit/EditContentForm/index.style.ts
  frontend/components/Pages/Offers/Edit/EditContentForm/index.tsx
  frontend/components/Pages/Offers/Filters/Period/index.tsx
  frontend/components/Pages/Offers/Filters/Sort/index.tsx
  frontend/components/Pages/Offers/Filters/Status/index.tsx
  frontend/components/Pages/Offers/Filters/index.tsx
  frontend/components/Pages/SingleOffer/TopOffers/index.tsx
  frontend/interfaces/index.ts
  frontend/next.config.js
  frontend/pages/offers/edit/[offerId]/index.tsx
  frontend/pages/offers/index.tsx
  frontend/pages/profile/private/my-offers/[offerStatus].tsx
  frontend/pages/profile/private/settings/[activeTab].tsx
  frontend/public/sw.js
  frontend/redux/config/reducer.ts
  frontend/redux/config/search/interfaces.ts
  frontend/redux/config/search/reducer.ts
  frontend/redux/config/searchHiddenBlocks/interfaces.ts
  frontend/redux/config/searchHiddenBlocks/reducer.ts
  frontend/redux/config/searchParams/interfaces.ts
  frontend/redux/config/searchParams/reducer.ts
  frontend/redux/state.ts
  frontend/redux/types.ts
Labels: FE

#114 Edit offer img
  frontend/assets/theme.ts
  frontend/components/common/load-more/pagination/index.tsx
  frontend/components/common/search/index.tsx
  frontend/components/context/auth/auth-interceptor/index.tsx
  frontend/components/layout/header/index.tsx
  frontend/components/layout/header/lang/index.tsx
  frontend/components/layout/header/user-info/index.tsx
  frontend/components/layout/meta/index.tsx
  frontend/components/layout/page-layout/index.tsx
  frontend/components/layout/tag-main/index.tsx
  frontend/components/pages/offers/edit/aside-element/index.tsx
  frontend/components/pages/offers/edit/edit-content-form/edit-content-form.style.ts
  frontend/components/pages/offers/edit/edit-content-form/index.tsx
  frontend/components/pages/offers/edit/edit-content-form/step-one/index.tsx
  frontend/components/pages/offers/edit/photos-upload-modal/index.tsx
  frontend/components/pages/offers/filters/index.tsx
  frontend/components/pages/single-offer/top-offers/index.tsx
  frontend/interfaces/index.ts
  frontend/middleware/persist.middleware.ts
  frontend/pages/index.tsx
  frontend/pages/offers/[offerId]/index.tsx
  frontend/pages/offers/edit/[offerId]/index.tsx
  frontend/pages/offers/index.tsx
  frontend/redux/config/reducer.ts
  frontend/redux/config/searchHiddenBlocks/interfaces.ts
  frontend/redux/config/searchHiddenBlocks/reducer.ts
  frontend/redux/offers/new_offer/saga.ts
  frontend/redux/offers/single/interfaces.ts
  frontend/redux/offers/single/reducer.ts
  frontend/redux/state.ts
  frontend/redux/types.ts
  frontend/styles/libs/uppy.core.css
  frontend/styles/libs/uppy.dashboard.css
Labels: FE

#118 Add general site config with cookies
  frontend/components/common/warning/index.tsx
  frontend/components/context/config/index.tsx
  frontend/components/context/theme/index.tsx
  frontend/components/pages/offers/filters/index.tsx
  frontend/components/pages/single-offer/top-offers/index.tsx
  frontend/hooks/config.hook.ts
  frontend/hooks/theme.hook.ts
  frontend/interfaces/index.ts
  frontend/pages/_app.tsx
Labels: FE

#119 Active filters list
  frontend/assets/theme.ts
  frontend/components/common/offers/offers-card/offers-card.styles.ts
  frontend/components/common/search/index.tsx
  frontend/components/pages/offers/active-filters/index.tsx
  frontend/components/pages/offers/filters/index.tsx
  frontend/components/pages/offers/filters/period/index.tsx
  frontend/components/pages/offers/filters/price/index.tsx
  frontend/components/pages/offers/filters/search-filters/index.tsx
  frontend/components/pages/offers/filters/sort/index.tsx
  frontend/components/pages/offers/filters/status/index.tsx
  frontend/components/pages/offers/filters/top-search-query/index.tsx
  frontend/pages/offers/index.tsx
Labels: FE

#120 Price filter
  frontend/components/common/offers/offers-card/index.tsx
  frontend/components/common/offers/offers-card/offers-card.styles.ts
  frontend/components/common/search/index.tsx
  frontend/components/pages/home/categories/index.tsx
  frontend/components/pages/offers/active-filters/index.tsx
  frontend/components/pages/offers/filters/price/index.tsx
  frontend/components/pages/offers/filters/sort/index.tsx
Labels: FE

#122 More animations
  frontend/assets/template.ts
  frontend/assets/theme.ts
  frontend/components/common/banner/index.tsx
  frontend/components/common/button-close/index.tsx
  frontend/components/common/comments/comments-form/index.tsx
  frontend/components/common/drop-down/index.tsx
  frontend/components/common/link-arrow/index.tsx
  frontend/components/common/logo/index.tsx
  frontend/components/common/modal/full-page-gallery/index.tsx
  frontend/components/common/modal/mid-modal-wrp/index.tsx
  frontend/components/common/nav-tabs/profile/profile.styles.ts
  frontend/components/common/nav-tabs/user-nav/index.tsx
  frontend/components/common/offers/offers-card/index.tsx
  frontend/components/common/offers/offers-card/offers-card.styles.ts
  frontend/components/common/offers/offers-list/index.tsx
  frontend/components/common/search/index.tsx
  frontend/components/common/search/options-mobile/index.tsx
  frontend/components/common/section-title/index.tsx
  frontend/components/common/switcher/index.tsx
  frontend/components/layout/footer/index.tsx
  frontend/components/layout/footer/site-map/index.tsx
  frontend/components/layout/header/index.tsx
  frontend/components/layout/header/lang/index.tsx
  frontend/components/layout/header/menu-icon/index.tsx
  frontend/components/layout/header/user-info/drop-window/index.tsx
  frontend/components/layout/header/user-info/index.tsx
  frontend/components/pages/home/categories/index.tsx
  frontend/components/pages/offers/active-filters/index.tsx
  frontend/components/pages/offers/edit/edit-content-form/edit-content-form.style.ts
  frontend/components/pages/offers/filters/filters.styles.ts
  frontend/components/pages/offers/filters/price/index.tsx
  frontend/components/pages/offers/filters/search-filters/index.tsx
  frontend/components/pages/offers/filters/top-search-query/index.tsx
  frontend/components/pages/offers/new/new-offer.style.ts
  frontend/components/pages/profile/private/settings/general/avatar/index.tsx
  frontend/components/pages/profile/private/settings/general/general-info-form/index.tsx
  frontend/components/pages/single-offer/requirements/index.tsx
  frontend/pages/index.tsx
  frontend/pages/offers/[offerId]/index.tsx
  frontend/styles/styles.css
  frontend/translate/index.ts
  frontend/translate/locales/en.json
  frontend/translate/locales/en/common.json
  frontend/translate/locales/pl.json
  frontend/translate/locales/pl/common.json
  frontend/translate/locales/ru.json
  frontend/translate/locales/ru/common.json
Labels: FE

#126 Static pages
  frontend/assets/config.ts
  frontend/assets/routes.ts
  frontend/assets/trans.ts
  frontend/components/common/about/index.tsx
  frontend/components/common/banner/index.tsx
  frontend/components/common/drawer/index.tsx
  frontend/components/common/nav-tabs/profile/chat-nav/index.tsx
  frontend/components/common/nav-tabs/profile/offers-nav/index.tsx
  frontend/components/common/nav-tabs/profile/profile.styles.ts
  frontend/components/common/nav-tabs/profile/root-nav/index.tsx
  frontend/components/common/nav-tabs/user-nav/index.tsx
  frontend/components/common/offers/offers-card/index.tsx
  frontend/components/common/offers/offers-card/offers-card.styles.ts
  frontend/components/common/offers/popular-offers/index.tsx
  frontend/components/common/search/index.tsx
  frontend/components/common/search/options-desktop/index.tsx
  frontend/components/common/search/options-mobile/index.tsx
  frontend/components/common/warning/index.tsx
  frontend/components/layout/footer/site-map/index.tsx
  frontend/components/layout/header/index.tsx
  frontend/components/layout/header/menu-icon/index.tsx
  frontend/components/layout/header/not-auth/index.tsx
  frontend/components/layout/header/user-info/index.tsx
  frontend/components/layout/main-drawer/auth-drawer/index.tsx
  frontend/components/layout/main-drawer/index.tsx
  frontend/components/layout/meta/index.tsx
  frontend/components/pages/home/categories/index.tsx
  frontend/components/pages/offers/edit/photos-upload-modal/index.tsx
  frontend/components/pages/offers/filters/search-filters/index.tsx
  frontend/components/pages/offers/filters/sort/index.tsx
  frontend/components/pages/profile/private/messages/chat-wrp/chat-sidebar/chat-sidebar-item/index.tsx
  frontend/components/pages/profile/private/messages/chat-wrp/chat-sidebar/index.tsx
  frontend/components/pages/profile/private/messages/chat-wrp/index.tsx
  frontend/components/pages/single-offer/top-offers/index.tsx
  frontend/interfaces/index.ts
  frontend/pages/auth/forgot-pass/index.tsx
  frontend/pages/auth/join/index.tsx
  frontend/pages/auth/login/index.tsx
  frontend/pages/favorite/index.tsx
  frontend/pages/index.tsx
  frontend/pages/offers/index.tsx
  frontend/pages/offers/new/[step]/index.tsx
  frontend/pages/profile/private/analytics/index.tsx
  frontend/pages/profile/private/messages/[chat]/index.tsx
  frontend/pages/profile/private/messages/index.tsx
  frontend/pages/profile/private/my-offers/[offerStatus].tsx
  frontend/pages/profile/private/referral/index.tsx
  frontend/pages/profile/private/reviews/index.tsx
  frontend/pages/profile/private/settings/[activeTab].tsx
  frontend/pages/profile/public/[profileId]/index.tsx
  frontend/pages/static/ad/index.tsx
  frontend/pages/static/faq/index.tsx
  frontend/pages/static/help/index.tsx
  frontend/pages/static/map/index.tsx
  frontend/pages/static/politic/index.tsx
  frontend/pages/static/rules/index.tsx
  frontend/pages/static/safety/index.tsx
  frontend/translate/locales/en.json
  frontend/translate/locales/pl.json
  frontend/translate/locales/ru.json
Labels: FE

#130 Mobile chat
  frontend/assets/helpers.ts
  frontend/components/common/mobile-nav/index.tsx
  frontend/components/pages/profile/private/messages/chat-conversation/chat-form/index.tsx
  frontend/components/pages/profile/private/messages/chat-search/index.tsx
  frontend/components/pages/profile/private/messages/chat-wrp/chat-sidebar/chat-sidebar-item/index.tsx
  frontend/components/pages/profile/private/messages/chat-wrp/chat-sidebar/index.tsx
  frontend/components/pages/profile/private/messages/chat-wrp/index.tsx
  frontend/components/pages/profile/private/settings/privacy/index.tsx
  frontend/components/pages/profile/private/settings/privacy/reset-email/index.tsx
  frontend/pages/profile/private/my-offers/[offerStatus].tsx
  frontend/styles/styles.css
Labels: FE

#121 added confirmation page and fixed favorite button
  frontend/assets/routes.ts
  frontend/components/pages/single-offer/offer-head/index.tsx
  frontend/pages/auth/confirmation/index.tsx
  frontend/public/about/bg_confirmation.jpg
Labels: FE

#135 New themes
  frontend/assets/config.ts
  frontend/assets/template.ts
  frontend/assets/theme.ts
  frontend/components/common/advertising/index.tsx
  frontend/components/common/banner/index.tsx
  frontend/components/common/comments/comments-form/index.tsx
  frontend/components/common/comments/comments-list/comments-item/index.tsx
  frontend/components/common/drop-down/index.tsx
  frontend/components/common/google-facebook/index.tsx
  frontend/components/common/input/index.tsx
  frontend/components/common/logo/index.tsx
  frontend/components/common/offers/offers-card/offers-card.styles.ts
  frontend/components/common/profile-card/index.tsx
  frontend/components/common/search/index.tsx
  frontend/components/common/search/options-mobile/index.tsx
  frontend/components/common/switcher/index.tsx
  frontend/components/common/user-avatar/index.tsx
  frontend/components/common/user-avatar/online-indicator/index.tsx
  frontend/components/common/user-nav/profile/chat-nav/index.tsx
  frontend/components/common/user-nav/profile/profile.styles.ts
  frontend/components/common/user-nav/profile/root-nav/index.tsx
  frontend/components/context/theme/index.tsx
  frontend/components/layout/header/index.tsx
  frontend/components/layout/header/lang/index.tsx
  frontend/components/layout/header/user-info/drop-window/index.tsx
  frontend/components/layout/header/user-info/index.tsx
  frontend/components/layout/main-drawer/auth-drawer/index.tsx
  frontend/components/layout/main-drawer/index.tsx
  frontend/components/layout/main-drawer/themes-list/index.tsx
  frontend/components/pages/home/categories/index.tsx
  frontend/components/pages/offers/edit/photos-upload-modal/index.tsx
  frontend/components/pages/offers/filters/search-filters/index.tsx
  frontend/components/pages/offers/new/new-offer.style.ts
  frontend/components/pages/offers/new/step-one/region/index.tsx
  frontend/components/pages/offers/new/step-three/index.tsx
  frontend/components/pages/profile/private/messages/chat-conversation/chat-form/index.tsx
  frontend/components/pages/profile/private/messages/chat-search/index.tsx
  frontend/hooks/theme.hook.ts
  frontend/interfaces/index.ts
  frontend/pages/_app.tsx
  frontend/pages/profile/private/my-offers/[offerStatus].tsx
  frontend/public/logo.svg
  frontend/styles/styles.css
Labels: FE
